#!/bin/bash

# Выход при ошибке
set -e

echo "🔧 Удаляю старый тег v0.1 (если есть)..."
git tag -d v0.1 || true
git push origin :refs/tags/v0.1 || true

echo "✅ Старый тег удалён"

echo "📝 Добавляю изменения и коммичу (если нужно)..."
git add action.yml README.md
git commit -m "Add GitHub Action for Dnsmasq config check" || echo "✅ Уже закоммичено"

echo "🏷 Создаю новый тег v0.1 на текущем коммите..."
git tag v0.1

echo "🚀 Публикую тег v0.1 на GitHub..."
git push origin v0.1

echo "✅ Всё готово. Теперь можно использовать Action как: mizoil/dnsmasq-action@v0.1"
